on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.CODECOV_GITHUB_PAT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Brew and macOS config
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install udunits
          brew install gdal
          cat <<EOT >> .Renviron
          PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
          PROJ_LIB=/usr/local/opt/proj/share/proj/
          # for installing XML package from source
          XML_CONFIG=/usr/local/opt/libxml2/bin/xml2-config
          EOT
          cat <<EOT >> .Rprofile
          r <- getOption("repos")
          r["CRAN"] <- "https://cran.rstudio.com"
          # r["rccp_drat"] <- "https://RcppCore.github.io/drat"
          config_args <- c("sf" = "--with-proj-lib=/usr/local/lib/", "rgdal" = "--with-proj-lib=/usr/local/lib/ --with-proj-include=/usr/local/include/")
          options(configure.args = config_args,
                  install.packages.compile.from.source = "yes",
                  repos = r)
          EOT

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-3.6-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-3.6-

      - name: Install dependencies
        run: |
          # install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("covr")
        shell: Rscript {0}
        
      - name: Install rgdal with configure
        if: runner.os == 'macOS'
        run: |
          install.packages("rgdal", type = "source", configure.args = "--with-proj-lib=/usr/local/lib/ --with-proj-include=/usr/local/include/")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
